server:
  port: 8081 
  servlet:
    context-path: /systex
    
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    suffix: .html
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name:
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
    